language: python
python:
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "pypy"
env:
  - DJANGO="Django>=1.6,<1.7"
  - DJANGO="Django>=1.7,<1.8"
  - DJANGO="Django>=1.8,<1.9"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install $DJANGO
# command to run tests, e.g. python setup.py test
script: cd tests/ && ./runtests.sh

# Run on travis' container infrastructure
sudo: false
